[env:m5stick-c-plus2]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
build_flags =
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DCORE_DEBUG_LEVEL=1
lib_deps =
	m5stack/M5Unified@^0.2.7
	m5stack/M5GFX@^0.2.7
	bblanchon/ArduinoJson@^7.3.0
